using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GESTIONBUDGETAPI.Module
{
    public class FDocEntete
    {
        public string? DO_Domaine { get; set; }
        public string? DO_Type { get; set; }
        public string? DO_Piece { get; set; }
        public string? cbDO_Piece { get; set; }
        public DateTime? DO_Date { get; set; }
        public string? DO_Ref { get; set; }
        public string? DO_Tiers { get; set; }
        public string? cbDO_Tiers { get; set; }
        public int? CO_No { get; set; }
        public string? cbCO_No { get; set; }
        public int? DO_Period { get; set; }
        public string? DO_Devise { get; set; }
        public decimal? DO_Cours { get; set; }
        public int? DE_No { get; set; }
        public string? cbDE_No { get; set; }
        public int? LI_No { get; set; }
        public string? cbLI_No { get; set; }
        public string? CT_NumPayeur { get; set; }
        public string? cbCT_NumPayeur { get; set; }
        public string? DO_Expedit { get; set; }
        public int? DO_NbFacture { get; set; }
        public int? DO_BLFact { get; set; }
        public decimal? DO_TxEscompte { get; set; }
        public int? DO_Reliquat { get; set; }
        public int? DO_Imprim { get; set; }
        public string? CA_Num { get; set; }
        public string? cbCA_Num { get; set; }
        public string? DO_Coord01 { get; set; }
        public string? DO_Coord02 { get; set; }
        public string? DO_Coord03 { get; set; }
        public string? DO_Coord04 { get; set; }
        public string? DO_Souche { get; set; }
        public DateTime? DO_DateLivr { get; set; }
        public string? DO_Condition { get; set; }
        public int? DO_Tarif { get; set; }
        public int? DO_Colisage { get; set; }
        public string? DO_TypeColis { get; set; }
        public int? DO_Transaction { get; set; }
        public string? DO_Langue { get; set; }
        public decimal? DO_Ecart { get; set; }
        public int? DO_Regime { get; set; }
        public int? N_CatCompta { get; set; }
        public int? DO_Ventile { get; set; }
        public int? AB_No { get; set; }
        public DateTime? DO_DebutAbo { get; set; }
        public DateTime? DO_FinAbo { get; set; }
        public DateTime? DO_DebutPeriod { get; set; }
        public DateTime? DO_FinPeriod { get; set; }
        public string? CG_Num { get; set; }
        public string? cbCG_Num { get; set; }
        public int? DO_Statut { get; set; }
        public TimeSpan? DO_Heure { get; set; }
        public int? CA_No { get; set; }
        public string? cbCA_No { get; set; }
        public int? CO_NoCaissier { get; set; }
        public string? cbCO_NoCaissier { get; set; }
        public int? DO_Transfere { get; set; }
        public int? DO_Cloture { get; set; }
        public int? DO_NoWeb { get; set; }
        public int? DO_Attente { get; set; }
        public int? DO_Provenance { get; set; }
        public string? CA_NumIFRS { get; set; }
        public int? MR_No { get; set; }
        public int? DO_TypeFrais { get; set; }
        public decimal? DO_ValFrais { get; set; }
        public int? DO_TypeLigneFrais { get; set; }
        public int? DO_TypeFranco { get; set; }
        public decimal? DO_ValFranco { get; set; }
        public int? DO_TypeLigneFranco { get; set; }
        public decimal? DO_Taxe1 { get; set; }
        public int? DO_TypeTaux1 { get; set; }
        public int? DO_TypeTaxe1 { get; set; }
        public decimal? DO_Taxe2 { get; set; }
        public int? DO_TypeTaux2 { get; set; }
        public int? DO_TypeTaxe2 { get; set; }
        public decimal? DO_Taxe3 { get; set; }
        public int? DO_TypeTaux3 { get; set; }
        public int? DO_TypeTaxe3 { get; set; }
        public int? DO_MajCpta { get; set; }
        public string? DO_Motif { get; set; }
        public string? CT_NumCentrale { get; set; }
        public string? cbCT_NumCentrale { get; set; }
        public string? DO_Contact { get; set; }
        public int? DO_FactureElec { get; set; }
        public int? DO_TypeTransac { get; set; }
        public DateTime? DO_DateLivrRealisee { get; set; }
        public DateTime? DO_DateExpedition { get; set; }
        public string? DO_FactureFrs { get; set; }
        public string? cbDO_FactureFrs { get; set; }
        public string? DO_PieceOrig { get; set; }
        public string? cbDO_PieceOrig { get; set; }
        public Guid? DO_GUID { get; set; }
        public int? DO_EStatut { get; set; }
        public int? DO_DemandeRegul { get; set; }
        public int? ET_No { get; set; }
        public string? cbET_No { get; set; }
        public int? DO_Valide { get; set; }
        public int? DO_Coffre { get; set; }
        public string? DO_CodeTaxe1 { get; set; }
        public string? DO_CodeTaxe2 { get; set; }
        public string? DO_CodeTaxe3 { get; set; }
        public decimal? DO_TotalHT { get; set; }
        public int? DO_StatutBAP { get; set; }
        public decimal? DO_Escompte { get; set; }
        public int? DO_DocType { get; set; }
        public int? DO_TypeCalcul { get; set; }
        public string? DO_FactureFile { get; set; }
        public decimal? DO_TotalHTNet { get; set; }
        public decimal? DO_TotalTTC { get; set; }
        public decimal? DO_NetAPayer { get; set; }
        public decimal? DO_MontantRegle { get; set; }
        public string? DO_RefPaiement { get; set; }
        public string? DO_AdressePaiement { get; set; }
        public string? DO_PaiementLigne { get; set; }
        public string? DO_MotifDevis { get; set; }
        public int? cbProt { get; set; }

        [Key]
        public int? cbMarq { get; set; }
        public string? cbCreateur { get; set; }
        public DateTime? cbModification { get; set; }
        public int? cbReplication { get; set; }
        public int? cbFlag { get; set; }
        public DateTime? cbCreation { get; set; }
        public string? cbCreationUser { get; set; }
        public string? cbHash { get; set; }
        public int? cbHashVersion { get; set; }
        public DateTime? cbHashDate { get; set; }
        public int? cbHashOrder { get; set; }
        public string? Commentaires { get; set; }
        public string? Divers { get; set; }
        public int? DO_Conversion { get; set; }
        public int? DO_TVADebit { get; set; }
        public int? EB_No { get; set; }
        public string? DO_RefExterne { get; set; }
        public int? CFAR_No { get; set; }
        public string? cbCFAR_No { get; set; }
        public int? FAC_No { get; set; }
        public string? cbFAC_No { get; set; }
        public int? DO_Exclure { get; set; }
        public string? DO_CodeService { get; set; }
    }
}
